; PlatformIO Project Configuration File

[common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_TYPE=1
    -DPSRAM_SIZE=2
    -DPSRAM_CLK=120000000
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude
    -Wno-deprecated-enum-enum-conversion
lib_deps =
    lvgl/lvgl@8.3.11
    bblanchon/ArduinoJson@^7.0.4
    lovyan03/LovyanGFX@^1.2.0
    adafruit/Adafruit SSD1306@^2.5.13
    tamctec/TAMC_GT911@^1.0.2
    bodmer/TJpg_Decoder

[env:esp32-s3-devkitc-1]
extends = common

[env:esp32-s3-devkitc-1-ota]
extends = common
upload_protocol = espota
upload_port = sonos-frame.local
